[program:NalamVazhaWebApi]
directory=/home/ubuntu/Automaton/AutomatonClient/wwwroot/PublishedFiles/NalamVazha/webapp/Publish/WebApi/
command=dotnet /home/ubuntu/Automaton/AutomatonClient/wwwroot/PublishedFiles/NalamVazha/webapp/Publish/WebApi/NalamVazhaWebApi.dll
autostart=true
autorestart=true
stderr_logfile=/var/log/NalamVazhaWebApi.err.log
stdout_logfile=/var/log/NalamVazhaWebApi.out.log
environment=ASPNETCORE_ENVIRONMENT=Production
user=ubuntu
stopsignal=INT


